export type Locale = "en" | "sk";
export const contactFormUrl = "https://tally.so/r/gD8EO4";
export const securityPath = {
  en: "/en/cybersecurity/",
  sk: "/kyberneticka-bezpecnost/",
} as const;

export const siteCopy = {
  en: {
    languageName: "English",
    languagePath: "/",
    nav: { about: "About", security: "Cybersecurity", hardware: "Private AI", automation: "AI automation", blog: "Blog", contact: "Start a conversation" },
    home: {
      eyebrow: "Cybersecurity · secure AI · practical engineering",
      title: "Build secure systems. Put AI to work with confidence.",
      brandLine: "Security-first engineering for software, infrastructure, and AI.",
      intro: "Frazik helps Slovak companies reduce software and infrastructure risk, strengthen delivery practices, and adopt private, useful AI with security built in.",
      primaryCta: "Explore cybersecurity",
      secondaryCta: "Read the blog",
      personalEyebrow: "The person behind Frazik",
      personalTitle: "Security is part of good engineering—not a final checkbox.",
      personalText: "Frazik is an independent security and AI engineering practice. I work with teams to find practical improvements, make secure delivery repeatable, and deploy AI in ways that respect their data and risk.",
      servicesEyebrow: "What I can help with",
      servicesTitle: "Security-first services for modern teams",
      processEyebrow: "A focused process",
      processTitle: "From understanding risk to lasting improvement.",
      process: [
        ["01", "Understand", "We clarify your systems, threat exposure, delivery practices, data, and business priorities."],
        ["02", "Prioritize", "We agree on proportionate controls and a focused plan—security improvement without needless friction."],
        ["03", "Improve", "We implement, document, and verify changes, with a clear path for your team to maintain them."],
      ],
      blogEyebrow: "Writing",
      blogTitle: "Practical notes on cybersecurity, DevSecOps, and responsible AI.",
      blogCta: "View all posts",
      ctaTitle: "Want to make your systems more resilient?",
      ctaText: "Start with a conversation about your software, infrastructure, security priorities, or AI plans.",
      contactCta: "Start a conversation",
    },
    services: {
      security: {
        eyebrow: "Application security · DevSecOps · AI security",
        title: "Make security a dependable part of how you build and operate.",
        intro: "Practical security engineering for software teams: identify meaningful risks, strengthen development and deployment workflows, and build safeguards around AI systems and sensitive data.",
        benefitsTitle: "Security improvements that fit your team",
        benefits: ["Application and architecture reviews with prioritized, actionable findings", "DevSecOps practices for code, dependencies, secrets, and CI/CD pipelines", "Threat modeling and secure design guidance for new features and systems", "Security controls for LLM and RAG deployments, including access, data handling, and evaluation"],
        stepsTitle: "A clear, collaborative engagement",
        steps: ["Scope systems, assets, and business-critical risks", "Review architecture, code, and delivery practices", "Agree prioritized remediation with owners and trade-offs", "Verify changes and leave your team with practical guidance"],
        cta: "Discuss a security review",
      },
      hardware: {
        eyebrow: "Private AI infrastructure · Bratislava and Slovakia",
        title: "Local LLM hardware that stays under your control.",
        intro: "Custom, hardened workstations and servers for teams that need capable AI while keeping sensitive information in a controlled environment.",
        benefitsTitle: "Built for your actual workload",
        benefits: ["Hardware sized for the models, users, and security requirements you have", "Private deployment with attention to access, updates, and network boundaries", "Model installation, performance tuning, backups, and monitoring", "Local maintenance, upgrades, and remote support for Bratislava customers"],
        stepsTitle: "What the engagement includes",
        steps: ["Workload, data, and threat assessment", "Component selection and secure build", "Model, access, and tooling setup", "Handover, documentation, and maintenance plan"],
        cta: "Discuss your setup",
      },
      automation: {
        eyebrow: "AI adoption · workflow automation",
        title: "Turn repetitive work into a system your team can trust.",
        intro: "A practical path from scattered AI experiments to secure assistants, connected workflows, and measurable time saved—with governance and human oversight considered from the start.",
        benefitsTitle: "AI that fits the way you work",
        benefits: ["Discover high-value, low-risk automation opportunities", "Build assistants around your documents, knowledge, and processes", "Connect existing tools instead of forcing a new platform", "Train the team, measure adoption, and improve what works"],
        stepsTitle: "From first idea to adoption",
        steps: ["Map the current workflow", "Prioritize a focused pilot", "Build and integrate the solution", "Roll out with guidance and measurement"],
        cta: "Plan an automation pilot",
      },
    },
  },
  sk: {
    languageName: "Slovenčina",
    languagePath: "/sk/",
    nav: { about: "O Fraziku", security: "Kyberbezpečnosť", hardware: "Súkromná AI", automation: "AI automatizácia", blog: "Blog", contact: "Začať rozhovor" },
    home: {
      eyebrow: "Kyberbezpečnosť · bezpečná AI · praktické inžinierstvo",
      title: "Budujte bezpečné systémy. Využívajte AI s istotou.",
      brandLine: "Bezpečnosť v základoch softvéru, infraštruktúry aj AI.",
      intro: "Frazik pomáha slovenským firmám znižovať riziká v softvéri a infraštruktúre, zlepšovať vývojové procesy a bezpečne zavádzať súkromnú AI.",
      primaryCta: "Služby kyberbezpečnosti",
      secondaryCta: "Čítať blog",
      personalEyebrow: "Človek za Frazikom",
      personalTitle: "Bezpečnosť patrí k dobrému vývoju, nie až na jeho koniec.",
      personalText: "Frazik je nezávislá prax v oblasti bezpečnosti a AI inžinierstva. Pomáham tímom nájsť praktické zlepšenia, zaviesť opakovateľne bezpečný vývoj a nasadzovať AI s ohľadom na dáta a riziká.",
      servicesEyebrow: "S čím vám pomôžem",
      servicesTitle: "Bezpečnostné služby pre moderné tímy",
      processEyebrow: "Sústredený proces",
      processTitle: "Od pochopenia rizík k dlhodobému zlepšeniu.",
      process: [["01", "Porozumieť", "Zmapujeme systémy, riziká, vývojové procesy, dáta a obchodné priority."], ["02", "Uprednostniť", "Dohodneme primerané opatrenia a konkrétny plán bez zbytočného brzdenia tímu."], ["03", "Zlepšiť", "Zmeny zrealizujeme, zdokumentujeme a overíme; tím dostane praktické odporúčania do budúcnosti."]],
      blogEyebrow: "Písanie",
      blogTitle: "Praktické poznatky o kyberbezpečnosti, DevSecOps a zodpovednej AI.",
      blogCta: "Zobraziť všetky články",
      ctaTitle: "Chcete zvýšiť odolnosť svojich systémov?",
      ctaText: "Začnime rozhovorom o vašom softvéri, infraštruktúre, bezpečnostných prioritách alebo plánoch s AI.",
      contactCta: "Napíšte mi o vašom projekte",
    },
    services: {
      security: {
        eyebrow: "Bezpečnosť aplikácií · DevSecOps · bezpečná AI",
        title: "Začleňte bezpečnosť do vývoja aj prevádzky systémov.",
        intro: "Praktické bezpečnostné inžinierstvo pre softvérové tímy: identifikácia dôležitých rizík, zlepšenie vývojových a nasadzovacích procesov a ochrana AI systémov a citlivých údajov.",
        benefitsTitle: "Zlepšenia prispôsobené vášmu tímu",
        benefits: ["Bezpečnostné a architektonické posúdenia s konkrétnymi prioritami", "DevSecOps postupy pre kód, závislosti, tajomstvá a CI/CD pipeline", "Modelovanie hrozieb a odporúčania pre bezpečný návrh systémov", "Ochrana LLM a RAG riešení vrátane prístupov, práce s dátami a testovania"],
        stepsTitle: "Jasná spolupráca s vaším tímom",
        steps: ["Určíme rozsah, systémy, aktíva a kritické riziká", "Posúdime architektúru, kód a spôsob nasadzovania", "Dohodneme priority nápravy, zodpovednosti a kompromisy", "Overíme zmeny a odovzdáme praktické odporúčania tímu"],
        cta: "Prediskutovať bezpečnostné posúdenie",
      },
      hardware: {
        eyebrow: "Súkromná AI infraštruktúra · Bratislava a Slovensko",
        title: "Lokálny hardvér pre LLM, ktorý zostáva pod vašou kontrolou.",
        intro: "Pracovné stanice a servery na mieru pre tímy, ktoré potrebujú výkonnú AI v kontrolovanom prostredí bez odosielania citlivých údajov verejnému poskytovateľovi modelu.",
        benefitsTitle: "Navrhnuté pre vašu skutočnú záťaž",
        benefits: ["Hardvér prispôsobený modelom, používateľom a bezpečnostným požiadavkám", "Súkromné nasadenie s dôrazom na prístupy, aktualizácie a sieťové hranice", "Inštalácia modelov, ladenie výkonu, zálohy a monitoring", "Lokálna údržba, rozšírenia a vzdialená podpora pre Bratislavu"],
        stepsTitle: "Čo spolupráca zahŕňa",
        steps: ["Analýza záťaže, dát a hrozieb", "Výber komponentov a bezpečné zostavenie", "Nastavenie modelov, prístupov a nástrojov", "Odovzdanie, dokumentácia a plán údržby"],
        cta: "Prediskutovať vaše riešenie",
      },
      automation: {
        eyebrow: "Adopcia AI · automatizácia procesov",
        title: "Zmeňte opakovanú prácu na systém, ktorému váš tím dôveruje.",
        intro: "Praktická cesta od izolovaných AI experimentov k bezpečným asistentom, prepojeným pracovným postupom a merateľnej úspore času – s dôrazom na správu a ľudský dohľad.",
        benefitsTitle: "AI, ktorá zapadne do vašej práce",
        benefits: ["Nájdeme príležitosti s vysokou hodnotou a nízkym rizikom", "Vytvoríme asistentov nad vašimi dokumentmi, znalosťami a procesmi", "Prepojíme existujúce nástroje bez nútenia novej platformy", "Zaškolíme tím, zmeriame používanie a zlepšíme, čo funguje"],
        stepsTitle: "Od prvého nápadu k používaniu",
        steps: ["Zmapovanie súčasného procesu", "Výber úzkeho pilotného projektu", "Vytvorenie a integrácia riešenia", "Nasadenie s podporou a meraním"],
        cta: "Naplánovať pilot automatizácie",
      },
    },
  },
} as const;

export function getCopy(locale: Locale) {
  return siteCopy[locale];
}
