export type Locale = "en" | "sk";
export const contactFormUrl = "https://tally.so/r/gD8EO4";

export const siteCopy = {
  en: {
    languageName: "English",
    languagePath: "/",
    nav: { about: "About", hardware: "Local AI", automation: "Automation", blog: "Blog", contact: "Start a conversation" },
    home: {
      eyebrow: "Personal expertise · practical AI services",
      title: "Useful AI, built around the way your business works.",
      brandLine: "From phrases to tokens. From tokens to useful work.",
      intro: "Frazik combines hands-on engineering with a personal, practical approach to help Slovak companies run private AI and automate meaningful work.",
      primaryCta: "Explore AI services",
      secondaryCta: "Read the blog",
      personalEyebrow: "The person behind Frazik",
      personalTitle: "Technology should make work clearer, not more complicated.",
      personalText: "Frazik is both a personal technical journal and a small AI engineering practice. The blog captures years of working with software; the services turn that experience into dependable systems for real teams.",
      servicesEyebrow: "What I can help with",
      servicesTitle: "Two practical ways to start",
      processEyebrow: "A focused process",
      processTitle: "From a useful question to a working system.",
      process: [
        ["01", "Understand", "We map the work, constraints, data, and the result that would actually matter."],
        ["02", "Design", "We choose the simplest secure architecture, whether that means local hardware, cloud services, or both."],
        ["03", "Deliver", "You get a working system, documentation, and a clear path for support and improvement."],
      ],
      blogEyebrow: "Writing",
      blogTitle: "Ideas, experiments, and lessons from building software.",
      blogCta: "View all posts",
      ctaTitle: "Have a process worth improving?",
      ctaText: "Start with a conversation about your data, your team, and what you want AI to do.",
      contactCta: "Start a conversation",
    },
    services: {
      hardware: {
        eyebrow: "Private AI infrastructure · Bratislava and Slovakia",
        title: "Local LLM hardware that stays under your control.",
        intro: "Custom workstations and servers for teams that need capable AI without sending sensitive information to a public model provider.",
        benefitsTitle: "Built for your actual workload",
        benefits: ["Hardware sized for the models and users you need", "Private deployment on your premises or in your controlled environment", "Model installation, performance tuning, backups, and monitoring", "Local maintenance, upgrades, and remote support for Bratislava customers"],
        stepsTitle: "What the engagement includes",
        steps: ["Workload and data assessment", "Component selection and build", "Secure model and tooling setup", "Handover, documentation, and maintenance plan"],
        cta: "Discuss your setup",
      },
      automation: {
        eyebrow: "AI adoption · workflow automation",
        title: "Turn repetitive work into a system your team can trust.",
        intro: "A practical path from scattered AI experiments to secure assistants, connected workflows, and measurable time saved.",
        benefitsTitle: "AI that fits the way you work",
        benefits: ["Discover high-value, low-risk automation opportunities", "Build assistants around your documents, knowledge, and processes", "Connect existing tools instead of forcing a new platform", "Train the team, measure adoption, and improve what works"],
        stepsTitle: "From first idea to adoption",
        steps: ["Map the current workflow", "Prioritize a focused pilot", "Build and integrate the solution", "Roll out with guidance and measurement"],
        cta: "Plan an automation pilot",
      },
    },
  },
  sk: {
    languageName: "Slovenčina",
    languagePath: "/sk/",
    nav: { about: "O Fraziku", hardware: "Lokálna AI", automation: "Automatizácia", blog: "Blog", contact: "Začať rozhovor" },
    home: {
      eyebrow: "Osobná expertíza · praktické AI služby",
      title: "Užitočná AI postavená okolo spôsobu, akým pracujete.",
      brandLine: "Od frázy k tokenom. Od tokenov k užitočnej práci.",
      intro: "Frazik spája praktické programátorské skúsenosti s osobným prístupom a pomáha slovenským firmám bezpečne využívať AI a automatizovať dôležitú prácu.",
      primaryCta: "Preskúmať AI služby",
      secondaryCta: "Čítať blog",
      personalEyebrow: "Človek za Frazikom",
      personalTitle: "Technológie majú prácu zjednodušiť, nie skomplikovať.",
      personalText: "Frazik je osobný technický blog aj malé AI inžinierske štúdio. Blog zachytáva roky práce so softvérom; služby premieňajú tieto skúsenosti na spoľahlivé systémy pre reálne tímy.",
      servicesEyebrow: "S čím vám pomôžem",
      servicesTitle: "Dva praktické spôsoby, ako začať",
      processEyebrow: "Sústredený proces",
      processTitle: "Od užitočnej otázky k fungujúcemu systému.",
      process: [["01", "Porozumieť", "Zmapujeme prácu, obmedzenia, dáta a výsledok, na ktorom skutočne záleží."], ["02", "Navrhnúť", "Vyberieme jednoduchú a bezpečnú architektúru – lokálny hardvér, cloud alebo ich kombináciu."], ["03", "Dodať", "Dostanete fungujúce riešenie, dokumentáciu a jasný plán podpory a ďalšieho zlepšovania."]],
      blogEyebrow: "Písanie",
      blogTitle: "Nápady, experimenty a skúsenosti z tvorby softvéru.",
      blogCta: "Zobraziť všetky články",
      ctaTitle: "Máte proces, ktorý sa dá zlepšiť?",
      ctaText: "Začnime rozhovorom o vašich dátach, tíme a o tom, čo má AI robiť.",
      contactCta: "Napíšte mi o vašom projekte",
    },
    services: {
      hardware: {
        eyebrow: "Súkromná AI infraštruktúra · Bratislava a Slovensko",
        title: "Lokálny hardvér pre LLM, ktorý zostáva pod vašou kontrolou.",
        intro: "Pracovné stanice a servery na mieru pre tímy, ktoré potrebujú výkonnú AI bez odosielania citlivých informácií verejnému poskytovateľovi modelu.",
        benefitsTitle: "Navrhnuté pre vašu skutočnú záťaž",
        benefits: ["Hardvér prispôsobený modelom a počtu používateľov", "Súkromné nasadenie u vás alebo v kontrolovanom prostredí", "Inštalácia modelov, ladenie výkonu, zálohy a monitoring", "Lokálna údržba, rozšírenia a vzdialená podpora pre Bratislavu"],
        stepsTitle: "Čo spolupráca zahŕňa",
        steps: ["Analýza záťaže a dát", "Výber komponentov a zostavenie", "Bezpečné nastavenie modelov a nástrojov", "Odovzdanie, dokumentácia a plán údržby"],
        cta: "Prediskutovať vaše riešenie",
      },
      automation: {
        eyebrow: "Adopcia AI · automatizácia procesov",
        title: "Zmeňte opakovanú prácu na systém, ktorému váš tím dôveruje.",
        intro: "Praktická cesta od izolovaných AI experimentov k bezpečným asistentom, prepojeným pracovným postupom a merateľnej úspore času.",
        benefitsTitle: "AI, ktorá zapadne do vašej práce",
        benefits: ["Nájdeme príležitosti s vysokou hodnotou a nízkym rizikom", "Vytvoríme asistentov nad vašimi dokumentmi, znalosťami a procesmi", "Prepojíme existujúce nástroje bez nútenia novej platformy", "Zaškolíme tím, zmeriame používanie a zlepšíme, čo funguje"],
        stepsTitle: "Od prvého nápadu k používaniu",
        steps: ["Zmapovanie súčasného procesu", "Výber úzkeho pilotného projektu", "Vytvorenie a integrácia riešenia", "Nasadenie s podporou a meraním"],
        cta: "Naplánovať pilot automatizácie",
      },
    },
  },
} as const;

export function getCopy(locale: Locale) {
  return siteCopy[locale];
}
